version: 0.2
env:
  variables:
    S3_BUCKET: raymond-packages-us-west-2

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - export APP_VERSION=1.0.0-$CODEBUILD_BUILD_NUMBER

      - mkdir build

      - zip -j -r build/lambda-hw2-${APP_VERSION}.zip lambda-hw2/
      - aws s3 cp build/lambda-hw2-${APP_VERSION}.zip s3://${S3_BUCKET}/hw2/lambda-hw2-${APP_VERSION}.zip

      - python cloudformation/deploy.py
