version: 0.2
env:
  variables:
    S3_BUCKET: raymond-packages-us-west-2
phases:
  build:
    commands:
      - zip -r lambda-example.zip . -x '*.git*'
      - aws ss cp lambda-example.zip s3://${S3_BUCKET}/lambda-example-1.0.0-${$CODEBUILD_BUILD_NUMBER}.zip