version: 0.2
env:

phases:
  install:
    runtime-versions:
      python: 3.8

  build:
    commands:
      - export APP_VERSION=1.0.0-$CODEBUILD_BUILD_NUMBER

      - mkdir build
      - zip -j -r build/lambda-hw2-${APP_VERSION}.zip lambda-hw2/

      - python cloudformation/deploy.py

artifacts:
  name: hw2
  base-directory: build
  files:
    - '*.zip'
